name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-rewview:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1.0.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          move to secrets!
          OPENAI_API_KEY: sk-27d33fb941b343ebb41eb2afd3222811
          LANGUAGE: Russian
          MODEL: openchat
          OPENAI_API_ENDPOINT: https://autotests.ai/adapter/v1
          PROMPT: "You are an experienced Java Automation QA developer and your job is to review pull requests. Please review the following code for any misunderstandings or violations. Don't spend time commenting on what is already working perfectly. I'm looking for constructive criticism and suggestions for improving the code, only useful and thorough notes."